name: Setup Crane
description: Install crane for use in Buildkite builds
author: https://github.com/sj26
requirements:
  - curl
  - jq
  - bash
configuration:
  properties:
    version:
      type: string
